#!/usr/bin/env php
<?php

use Akhaled\Ecommerce\Core\Facade\DatabaseConnection;

require __DIR__.'/../vendor/autoload.php';

(new \Akhaled\Ecommerce\Core\Bootstrap\Application)->bootstrap();

DatabaseConnection::query(
    file_get_contents(__DIR__ . "/schema.sql")
);

echo "Seed completed!\n";
